# Generated by Django 5.2.14 on 2026-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=50)),
                ('flight_name', models.CharField(max_length=30)),
                ('flight_number', models.IntegerField()),
                ('flight_from', models.CharField(max_length=20)),
                ('flight_to', models.CharField(max_length=20)),
                ('flight_depaturetime', models.CharField(max_length=20)),
                ('flight_date', models.CharField(max_length=20)),
                ('flight_price', models.IntegerField()),
            ],
        ),
    ]
