# Generated by Django 5.2.14 on 2026-05-15 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_flightmodel_flight_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='passengermodel',
            new_name='Bookinmodel',
        ),
    ]
