# Generated by Django 5.2.14 on 2026-05-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_passengermodel_bookinmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookinmodel',
        ),
    ]
