# Generated by Django 5.2.14 on 2026-05-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_bookinmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=50)),
                ('flight_name', models.CharField(max_length=30)),
                ('flight_number', models.CharField()),
                ('flight_from', models.CharField(max_length=20)),
                ('flight_to', models.CharField(max_length=20)),
                ('flight_depaturetime', models.CharField(max_length=20)),
                ('flight_date', models.CharField(max_length=20)),
                ('flight_price', models.IntegerField()),
                ('pname', models.CharField(max_length=30)),
                ('pemail', models.TextField(max_length=50)),
                ('p_phone_no', models.IntegerField(max_length=10)),
                ('p_Adhar_no', models.IntegerField(max_length=12)),
                ('p_age', models.IntegerField(max_length=4)),
                ('p_seat_class', models.CharField(max_length=20)),
                ('seat_num', models.IntegerField(max_length=10)),
            ],
        ),
    ]
