# Generated by Django 5.2.14 on 2026-05-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_bookinmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookinmodel',
            new_name='Bookingmodel',
        ),
    ]
