# Generated by Django 5.2.14 on 2026-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_bookinmodel_bookingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historymodel',
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='p_Adhar_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='p_phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='seat_num',
            field=models.IntegerField(),
        ),
    ]
