# Generated by Django 5.2.14 on 2026-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_historymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='flight_number',
            field=models.CharField(),
        ),
    ]
