from django.db import models

# Create your models here.
class usermodel(models.Model):
    user_name=models.CharField(max_length=20)
    user_password=models.IntegerField()
    user_email=models.TextField(max_length=40)
    user_fname=models.CharField(max_length=20)
    user_lname=models.CharField(max_length=20)
class flightmodel(models.Model):
    flight_company=models.CharField(max_length=50)
    flight_name=models.CharField(max_length=30)
    flight_number=models.CharField()
    flight_from=models.CharField(max_length=20)
    flight_to=models.CharField(max_length=20)
    flight_depaturetime=models.CharField(max_length=20)
    flight_date=models.CharField(max_length=20)
    flight_price=models.IntegerField()    
class historymodel(models.Model):
    flight_company=models.CharField(max_length=50)
    flight_name=models.CharField(max_length=30)
    flight_number=models.CharField()
    flight_from=models.CharField(max_length=20)
    flight_to=models.CharField(max_length=20)
    flight_depaturetime=models.CharField(max_length=20)
    flight_date=models.CharField(max_length=20)
    flight_price=models.IntegerField()
    pname=models.CharField(max_length=30)
    pemail=models.TextField(max_length=50)
    p_phone_no=models.IntegerField()
    p_Adhar_no=models.IntegerField()
    p_age=models.IntegerField(max_length=4)
    p_seat_class=models.CharField(max_length=20)
    seat_num=models.IntegerField()
class Bookingmodel(models.Model):
    flight_company=models.CharField(max_length=50)
    flight_name=models.CharField(max_length=30)
    flight_number=models.CharField()
    flight_from=models.CharField(max_length=20)
    flight_to=models.CharField(max_length=20)
    flight_depaturetime=models.CharField(max_length=20)
    flight_date=models.CharField(max_length=20)
    flight_price=models.IntegerField() 
    pname=models.CharField(max_length=30)
    pemail=models.TextField(max_length=50)
    p_phone_no=models.IntegerField()
    p_Adhar_no=models.IntegerField()
    p_age=models.IntegerField(max_length=4)
    p_seat_class=models.CharField(max_length=20)
    seat_num=models.IntegerField()
